### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ririko5834** [diwasatreya/Discord-ChatBOT#2]
The bot keeps replying with `The chatbot endpoint is currently having issues and will be resolved asap.`
It does this last month, before it worked.

**Comment by diwasatreya** [comment]
> The bot keeps replying with `The chatbot endpoint is currently having issues and will be resolved asap.` It does this last month, before it worked.

Package used in chatbot is not woking so we are making our own chatbot API. I will update this repo soon.
